name: Kong decK Sync

on:
  push:
    paths:
      - 'kong-konnect-deck/**'
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy (dev/staging/prod)"
        required: true
        default: "dev"

jobs:
  deck-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install decK
        uses: kong/setup-deck@v1
        with:
          deck-version: v1.60.0

      - name: Validate Kong Config
        run: |
          deck file validate \
            kong-konnect-deck/services/flight-bookings-service.yaml \
            kong-konnect-deck/routes/flights-route.yaml \
            kong-konnect-deck/plugins/rate-limiting.yaml

      - name: Diff (Preview Changes)
        run: |
          deck gateway diff \
            --konnect-token ${{ secrets.KONNECT_TOKEN }} \
            --konnect-control-plane-name demo-control-plane \
            kong-konnect-deck/services/flight-bookings-service.yaml \
            kong-konnect-deck/routes/flights-route.yaml \
            kong-konnect-deck/plugins/rate-limiting.yaml

      - name: Sync to Konnect
        run: |
          deck gateway sync \
            --konnect-token ${{ secrets.KONNECT_TOKEN }} \
            --konnect-control-plane-name demo-control-plane \
            kong-konnect-deck/partials/redis-partial.yaml \
            kong-konnect-deck/services/flight-bookings-service.yaml \
            kong-konnect-deck/routes/flights-route.yaml \
            kong-konnect-deck/plugins/rate-limiting.yaml